---
version: '3'
services:
  umami:
    image: ghcr.io/robot-ux/umami:mysql-latest
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: mysql://umami:umami@192.168.0.101:3306/umami
      DATABASE_TYPE: mysql
      HASH_SALT: replace-me-with-a-random-string
